language: java

jdk:
  - oraclejdk8

script:
  - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_BUCKET=${AWS_BUCKET}

deploy:
  - provider: openshift
    user: $OPENSHIFT_USER
    password: $OPENSHIFT_PASSWORD
    domain: $OPENSHIFT_DOMAIN
    app: datasafe-rest-service
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '!*datasafe-business*' -F unittests
  - bash <(curl -s https://codecov.io/bash) -f '*datasafe-business*' -F e2e_tests