language: java

jdk:
  - oraclejdk8

script:
  - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_ACCESS_KEY=${AWS_ACCESS_KEY} -DAWS_SECRET_KEY=${AWS_SECRET_KEY}

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '!*datasafe-business*' -F unittests
  - bash <(curl -s https://codecov.io/bash) -f 'datasafe-business*' -F e2e_tests