language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

# travis is quite limited for multi-language projects when one needs to share artifacts:
# https://github.com/travis-ci/travis-ci/issues/4090

script:
  - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_BUCKET=${AWS_BUCKET}
# make frontend available for REST-docker
  - cd frontend/datasafe-ui && ng build --deploy-url /static/ --base-href /static/ && mv dist ../../datasafe-rest-impl/dist && cd ../..

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"

  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/deploy_develop_to_openshift.sh
    on:
      branch: develop

before_install:
  - curl -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz > oc-cli.tar.gz
  - tar -xzf oc-cli.tar.gz
  - sudo mv ./openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/local/bin

# preparations to build frontend
install:
  - nvm install 11.12.0
  - cd frontend/datasafe-ui && npm install && cd ../..

after_success:
  - /bin/bash .travis/codecov_bash.sh