# Using bash because Travis CI does not support Java on Windows

branches:
  except:
    - gh-pages
env:
  global:
    # This is a convenience variable for shortening download commands
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - JDK="graalvm@19.2.0"

matrix:
  include:
    # This is original build and deploy, that runs E2E tests and deploys docker images
    - os: linux
      language: java

    # These are CLI-only builds that produce Datasafe cli executable for each OS:
    # CLI for Linux:
    - os: linux
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
    # CLI for MacOS:
    - os: osx
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
    # CLI for Windows:
    - os: windows
      env:
        - NO_WIN_DEFENDER=$(curl "${GRAVIS}.disable-windows-defender.sh" --output .no-defender.sh && source .no-defender.sh)
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh


before_install:
  - echo "Before install"

install:
  - echo "Install"

script:
  - echo "Script"

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "Deploy"

after_success:
  - echo "Success"
