# Using bash because Travis CI does not support Java on Windows

branches:
  except:
    - gh-pages
env:
  global:
    # This is a convenience variable for shortening download commands
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - JDK="graalvm@19.2.0"

build-cli: &build-cli
  script:
    # Prepare everything
    - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_BUCKET=${AWS_BUCKET} -DskipTests
    # Change security provides of JDK
    - /bin/bash .travis/enable_bouncycastle_security.sh
    # Build binaries
    - mvn --settings .travis/settings.xml -f datasafe-cli/pom.xml -Pnative-image clean package -B -V -DAWS_BUCKET=${AWS_BUCKET} -DskipTests

before_install:
  - echo "Before install"

install:
  - echo "Install"

script:
  - echo "Script"
  - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_BUCKET=${AWS_BUCKET} -DskipTests # FIXME remove skipTests

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "Deploy"

after_success:
  - echo "Success"

matrix:
  include:
    # This is original build and deploy, that runs E2E tests and deploys docker images
    - os: linux
      language: java

    # These are CLI-only builds that produce Datasafe cli executable for each OS:
    # CLI for Linux:
    - os: linux
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
      <<: *build-cli
    # CLI for MacOS:
    - os: osx
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
      <<: *build-cli
    # CLI for Windows:
    - os: windows
      env:
        - NO_WIN_DEFENDER=$(curl "${GRAVIS}.disable-windows-defender.sh" --output .no-defender.sh && source .no-defender.sh)
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
      <<: *build-cli
